baseurl: "https://example.com"
languageCode: "en-us"
title: "WittyJudge"
theme: "hugo-tania"
paginate: 6

disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  # titleEmoji:
  # Logo will show before the blog title on site navbar.
  # titleLogo: favicon.ico

  brand:
    emoji: 'üë®üèªüíª'
    # text: 'WittyJudge'
    # logo: logo/coffee.ico
 
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
 
  siteName: "WittyJudge personal blog, rss feed, csv"
  siteDesc: "WittyJudge personal blog, rss feed, csv"
  author: "WittyJudge"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email: 'ruslan.kondratyuk.dev@gmail.com'
    facebook:
    github: 'https://github.com/wittyjudge'
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:
  
  # Comments settings
  comments:
    enabled: false
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: MDEwOlJlcG9zaXRvcnkzMTYyNjQzMDc=
      category:
        name: Comments
        id: DIC_kwDOEtnPc84B_WKP

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

# https://gohugo.io/content-management/syntax-highlighting/
markup:
  highlight:
    noClasses: false
    lineNos: false
    # style: monokai
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]

